#!/bin/bash

make build && make readme > /dev/null

response=$(gofmt -l src/sack/*.go)

if [[ $response == "" ]];then
  # TODO:
  # files=$(./bin/has-changed-bins)
  # exit_val=$?
  # echo $exit_val

  # if [[ $files != "" ]];then
  #   echo "Binaries have changed: Stage and commit ($files)"
  #   exit 1
  # fi
  val=""
else
  echo "Linting needed: $response"
  make lint

  exit 1
fi

