#!/bin/bash

url="https://github.com/zph/go-sack/releases/download/v0.3.0/sack"
bin_path="$HOME/bin/sack"

echo "Installing sack"
echo "Source: $url"
echo "Output: $bin_path"

wget -O $bin_path $url && chmod +x $bin_path

if [[ $? == 0 ]];then
  echo "Successfully installed"
else
  echo "Install failed please report an issue"
fi
